from os import getenv

SERVICE_RUNTIME = getenv('SERVICE_RUNTIME', 'locally')
SERVICE_PORT = int(getenv('SERVICE_PORT', 3001))
SERVICE_HOST = getenv('SERVICE_HOST', '0.0.0.0')

USER_MANAGEMENT_SERVICE_HOST = getenv('USER_MANAGEMENT_SERVICE_HOST', '0.0.0.0')
USER_MANAGEMENT_SERVICE_PORT = int(getenv('USER_MANAGEMENT_SERVICE_PORT', 3000))